version: '3.1'
services:
    web:
        build: .
        restart: always
        ports:
            - 80:80
        expose:
            - 80
        volumes:
            - ./htdocs:/var/www/html/
            - ./log/apache2:/var/log/apache2
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: coreDB
            MYSQL_USER: coreUser
            MYSQL_PASSWORD: corePW
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - ./mysql:/var/lib/mysql/
    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - mysql
        restart: always
        ports:
            - 8080:80
        expose:
            - 8080
        environment:
            PMA_HOSTS: mysql
            PMA_PORTS: 3306
            MYSQL_ROOT_PASSWORD: root